Add secp256k1 private key
multiformats/multicodec pull request #210
Opened 2021-05-08 19:46 UTC by OR13

Reasoning:

There already exists and ed25519 priv key.

Without the ability to represent both public and private components of asymmetric key pairs users will be forced for do things like this:

```
'id': '',
'type': 'EcdsaSecp256k1VerificationKey2020',
'controller': 'did:example:123',
'publicKeyMultibase': 'zQ3shU9mxTYfMTLceuppoNM5siowHvw3xBk21r855kwgNHNAX',
'privateKeyBase58': '6GyEn649EsbEEJXGQ5m8Eq6NANDmHTPQPWGyF5uL7kx8'
```

This prevents efficient compression using multibase codecs.

2021-05-10 18:06 UTC, OR13 commented on table.csv
> +secp256k1-priv,                 key,            0xe8,           draft,     Secp256k1 private key
```suggestion
secp256k1-priv,                 key,            0x1301,           draft,     Secp256k1 private key
```

2021-05-10 18:06 UTC, OR13 commented on table.csv
> +secp256k1-priv,                 key,            0xe8,           draft,     Secp256k1 private key
implemented in https://github.com/multiformats/multicodec/pull/210/commits/016319e1cf9a1a26269ffc6b4ed8ff86c05066a9

2021-05-10 18:46 UTC, OR13 commented
@rvagg thanks for the review! 

@msporny and I have been having this argument for years :)

Its not as much of an issue with JSON-LD when you can just pretend that not defining the term is somehow making it safer to to do this:


```
'id': '',
'type': 'EcdsaSecp256k1VerificationKey2020',
'controller': 'did:example:123',
'publicKeyBase58': 'zQ3shU9mxTYfMTLceuppoNM5siowHvw3xBk21r855kwgNHNAX',
'privateKeyBase58': '6GyEn649EsbEEJXGQ5m8Eq6NANDmHTPQPWGyF5uL7kx8'
```

The "problem" with multibase... is that you can't not define the entry... and still use it to represent a private key... like you can with JSON-LD.

Folks using JSON-LD with `privateKeyBase58` or `privateKeyMultibase` can decide if omitting context definitions is a security feature or not... but certainly nobody can even create a `privateKeyMultibase` without a registry entry here... 

the alternative to defining `privateKeyMultibase` is to use `privateKeyJwk`, which already preserves key type information and public key representations, and relies on IANA... in order for multibase to ever improve on JWK, it must be at least as expressive, imo... its a show stopper for our adoption of it.. if we can't represent privateKeyMultibase for the key types we use, we will just keep using privateKeyJwk... I expect most developers will do the same when they realize they cannot completely represent a private key.

2021-05-11 03:37 UTC, rvagg requested changes

2021-05-11 03:37 UTC, rvagg commented on table.csv
> +secp256k1-priv,                 key,            0x1301,           draft,     Secp256k1 private key
```suggestion
secp256k1-priv,                 key,            0x1301,         draft,     Secp256k1 private key
```
sorry, two stray chars now

2021-05-11 23:42 UTC, rvagg approved these changes

2021-05-11 23:43 UTC, merged