Adding multicodec for aes-gcm
multiformats/multicodec pull request #314
Opened 2023-02-14 07:37 UTC by guillaumemichel

Adding `aes-gcm-256` multicodec. Please edit if the category `encryption` doesn't fit here.

`aes-gcm-256` is a payload format: the 12-byte Initialization Vector (IV) is concatenated with a payload encrypted using AES in Galois/Counter Mode, using a 256-bit key and the 12 byte IV.

This multicodec is required for the Double Hash DHT https://github.com/ipfs/specs/pull/373

2023-02-14 11:21 UTC, vmx reviewed
Sounds reasonable to me. I've had a brief look at the corresponding section in the Double Hash DHT spec. Please note that the encoded value won't be `0xa5`, but the varint of it: `0xa501`.

Though I'd like to get input from others as this introduces a new category.

2023-02-20 05:05 UTC, rvagg requested changes
Since this opens the door to a massive number of permutations, all under the same "encryption" category, I think this should go later in the table where there is a sizeable chunk of free space.

Otherwise I don't mind a new category .. there's just a lot of them and I can imagine the inevitable PR with someone adding _all the possible permutations_ ..

2023-02-20 08:26 UTC, guillaumemichel commented
Moved `aes-gcm-256` to `0x2000`

```
code               varint
8192 (0x2000)   => 10000000 01000000 (0x8040)
```

2023-02-20 09:11 UTC, rvagg approved these changes
nice 👌

2023-02-23 00:17 UTC, merged