Add BLS12-381 private key entries
multiformats/multicodec pull request #340
Opened 2023-12-17 01:40 UTC by msporny

This PR adds the BLS12-381 private key entries.

2023-12-17 18:24 UTC, dlongley approved these changes

2023-12-17 22:54 UTC, rvagg requested changes

2023-12-17 22:54 UTC, rvagg commented on table.csv
> +bls12_381-g1g2-priv             key,            0x130b,         draft,      BLS12-381 G1 and G2 private key
```suggestion
bls12_381-g1-priv,              key,            0x1309,         draft,      BLS12-381 G1 private key
bls12_381-g2-priv,              key,            0x130a,         draft,      BLS12-381 G2 private key
bls12_381-g1g2-priv,            key,            0x130b,         draft,      BLS12-381 G1 and G2 private key
```

2023-12-18 01:48 UTC, rvagg approved these changes

2023-12-18 01:49 UTC, merged